apiVersion: v1
kind: Pod
metadata:
  name: aks-imex-daemon-pod
spec:
  containers:
    - name: aks-imex-daemon
      image: alexbenncr.azurecr.io/aks-imex/aks-imex-daemon:latest
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  restartPolicy: Never
