// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.3, generator: @autorest/go@4.0.0-preview.69)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package imds_generated

const host = "http://169.254.169.254/metadata"

type BypassCache string

const (
	BypassCacheTrue BypassCache = "true"
)

// PossibleBypassCacheValues returns the possible values for the BypassCache const type.
func PossibleBypassCacheValues() []BypassCache {
	return []BypassCache{	
		BypassCacheTrue,
	}
}

type Enum1 string

const (
	Enum1True Enum1 = "true"
)

// PossibleEnum1Values returns the possible values for the Enum1 const type.
func PossibleEnum1Values() []Enum1 {
	return []Enum1{	
		Enum1True,
	}
}

// Error - Error code
type Error string

const (
	ErrorAccessDenied Error = "access_denied"
	ErrorBadRequest Error = "bad_request"
	ErrorForbidden Error = "forbidden"
	ErrorInvalidRequest Error = "invalid_request"
	ErrorInvalidScope Error = "invalid_scope"
	ErrorMethodNotAllowed Error = "method_not_allowed"
	ErrorNotFound Error = "not_found"
	ErrorServerError Error = "server_error"
	ErrorServiceUnavailable Error = "service_unavailable"
	ErrorTooManyRequests Error = "too_many_requests"
	ErrorUnauthorizedClient Error = "unauthorized_client"
	ErrorUnsupportedResponseType Error = "unsupported_response_type"
)

// PossibleErrorValues returns the possible values for the Error const type.
func PossibleErrorValues() []Error {
	return []Error{	
		ErrorAccessDenied,
		ErrorBadRequest,
		ErrorForbidden,
		ErrorInvalidRequest,
		ErrorInvalidScope,
		ErrorMethodNotAllowed,
		ErrorNotFound,
		ErrorServerError,
		ErrorServiceUnavailable,
		ErrorTooManyRequests,
		ErrorUnauthorizedClient,
		ErrorUnsupportedResponseType,
	}
}

// HostOptions - choices for server host
type HostOptions string

const (
// HostOptionsHttp169254169254Metadata - host: http://169.254.169.254/metadata
	HostOptionsHttp169254169254Metadata HostOptions = "http://169.254.169.254/metadata"
// HostOptionsHttps169254169254Metadata - host: https://169.254.169.254/metadata
	HostOptionsHttps169254169254Metadata HostOptions = "https://169.254.169.254/metadata"
)

// PossibleHostOptionsValues returns the possible values for the HostOptions const type.
func PossibleHostOptionsValues() []HostOptions {
	return []HostOptions{	
		HostOptionsHttp169254169254Metadata,
		HostOptionsHttps169254169254Metadata,
	}
}

