// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.3, generator: @autorest/go@4.0.0-preview.69)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package imds_generated

// AttestedClientGetDocumentOptions contains the optional parameters for the AttestedClient.GetDocument method.
type AttestedClientGetDocumentOptions struct {
// This is a string of up to 32 random alphanumeric characters.
	Nonce *string
}

// IdentityClientGetInfoOptions contains the optional parameters for the IdentityClient.GetInfo method.
type IdentityClientGetInfoOptions struct {
	// placeholder for future optional parameters
}

// IdentityClientGetTokenOptions contains the optional parameters for the IdentityClient.GetToken method.
type IdentityClientGetTokenOptions struct {
// This indicates the authority to request AAD tokens from. Defaults to the known authority of the identity to be used.
	Authority *string

// If provided, the value must be 'true'. This indicates to the server that the token must be retrieved from Azure AD and
// cannot be retrieved from an internal cache.
	BypassCache *BypassCache

// This identifies, by Azure AD client id, a specific explicit identity to use when authenticating to Azure AD. Mutually exclusive
// with objectid and msires_id.
	ClientID *string

// This identifies, by urlencoded ARM resource id, a specific explicit identity to use when authenticating to Azure AD. Mutually
// exclusive with clientid and objectid.
	MsiResID *string

// This identifies, by Azure AD object id, a specific explicit identity to use when authenticating to Azure AD. Mutually exclusive
// with clientid and msires_id.
	ObjectID *string
}

// InstanceMetadataClientGetVersionsOptions contains the optional parameters for the InstanceMetadataClient.GetVersions method.
type InstanceMetadataClientGetVersionsOptions struct {
	// placeholder for future optional parameters
}

// InstancesClientGetMetadataOptions contains the optional parameters for the InstancesClient.GetMetadata method.
type InstancesClientGetMetadataOptions struct {
	// placeholder for future optional parameters
}

